# Generated by Django 5.2.4 on 2025-07-23 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RiskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('probability', models.CharField(choices=[('rare', 'Rare (<10%)'), ('unlikely', 'Unlikely (10-30%)'), ('possible', 'Possible (30-50%)'), ('likely', 'Likely (50-70%)'), ('certain', 'Certain (>70%)')], max_length=20)),
                ('contingency_plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Log',
                'verbose_name_plural': 'Risk Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
