# Generated by Django 5.2.4 on 2025-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_schel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='id',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
