# Generated by Django 5.2.4 on 2025-07-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
        ("projects", "0002_remove_project_id_alter_project_project_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="projects.project",
            ),
        ),
    ]
